version: '3.7'

services:
  smartmeter.example.com:
    container_name: smartmeter.example.com
    build: ./smart-meter
    volumes: 
      - ./smart-meter:/home/smartmeter
    command: uvicorn main:app --reload --host 0.0.0.0
    ports: 
      - 3001:8000