version: '3.7'

services:
  smartmeter.example.com:
    container_name: smartmeter.example.com
    build: ./smart-meter
    volumes: 
      - ./smart-meter:/home/smartmeter
    # command: bash
    command: flask run --host 0.0.0.0
    environment: 
      FLASK_APP: src/app.py
      FLASK_DEBUG: 1
    ports: 
      - 6000:5000